version: "3"

services:
  backend:
    build:
      context: ./backend
    container_name: strapi
    ports:
      - "1337:1337"
    # environment:
    #   NODE_ENV: development
    #   DATABASE_CLIENT: sqlite
    # working_dir: /app/backend
    command: yarn start

volumes:
  backend_node_modules:

  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app/frontend
  #     - /app/frontend/node_modules
  #   environment:
  #     NODE_ENV: development
  #   working_dir: /app/frontend
  #   command: yarn dev