version: "3"

services:
  backend:
    build:
      context: ./backend
    container_name: strapi
    ports:
      - "1337:1337"
    volumes:
      - ./backend:/srv/app/.tmp
      - ./backend/public/uploads:/app/public/uploads
    command: yarn start

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    command: yarn dev

volumes:
  backend_node_modules: