name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if dependencies have changed
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
            cd ${{ secrets.TARGET_DIR }} &&
            chmod +x deploy.sh &&
            ./deploy.sh
          "

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Copy project files to server
        run: |
          rsync -avz --exclude '.git' ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.TARGET_DIR }}

      - name: Restart containers
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
            cd ${{ secrets.TARGET_DIR }} &&
            docker-compose up -d --build
          "