name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts || true

      - name: Copy project files to server
        run: |
          rsync -avz --delete \
              --filter='protect backend/.tmp/' \
              --filter='protect backend/public/uploads/' \
              --exclude '.git' \
              ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.TARGET_DIR }}

      - name: Create backend .env file on server
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} '
            cat <<EOF > ${{ secrets.TARGET_DIR }}/backend/.env
            APP_KEYS=${{ secrets.APP_KEYS }}
            API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }}
            ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }}
            TRANSFER_TOKEN_SALT=${{ secrets.TRANSFER_TOKEN_SALT }}
            DATABASE_CLIENT=${{ secrets.DATABASE_CLIENT }}
            DATABASE_FILENAME=${{ secrets.DATABASE_FILENAME }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            PAYPAL_SECRET=${{ secrets.PAYPAL_SECRET }}
            PAYPAL_CLIENT_ID=${{ secrets.PAYPAL_CLIENT_ID }}
            NEXT_PUBLIC_HOST=${{ secrets.NEXT_PUBLIC_HOST }}
            NEXT_PUBLIC_SERVER_HOST=${{ secrets.NEXT_PUBLIC_SERVER_HOST }}
          '

      - name: Create frontend .env file on server
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} '
            cat <<EOF > ${{ secrets.TARGET_DIR }}/frontend/.env
            NEXT_PUBLIC_SERVER_HOST=${{ secrets.NEXT_PUBLIC_SERVER_HOST }}
          '

      - name: Clean up dangling images and restart containers
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} '
            cd ${{ secrets.TARGET_DIR }} &&
            docker-compose down --remove-orphans &&
            docker image prune -f &&
            docker container prune -f &&
            docker-compose up -d --build
          '