name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if backend/package.json changed
        id: check_package_json
        run: |
          echo "changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^backend/package.json$' && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Copy project files to server
        run: |
          rsync -avz --exclude '.git' ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.TARGET_DIR }}

      - name: Run deploy script and restart containers
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd ${{ secrets.TARGET_DIR }} && chmod +x deploy.sh && ./deploy.sh && docker-compose up -d --build"